development:
  sessions:
    default:
      database: bigdata_demo_development
      hosts:
        - localhost:27017 
production:
  sessions:
    default:
      database: bigdata_demo_production
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: bigdata_demo_test
      hosts:
        - localhost:27017
