development:
  sessions:
    default:
      database: linkedin_clone_development
      hosts:
        - localhost:27017 
production:
  sessions:
    default:
      database: linkedin_clone_production
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: linkedin_clone_test
      hosts:
        - localhost:27017
